apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eligible-chocolate-tortoise
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eligible-chocolate-tortoise 
  name: eligible-chocolate-tortoise
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eligible-chocolate-tortoise 
